// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package forgotpassword.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GenerateURL extends CustomJavaAction<java.lang.String>
{
	private java.lang.String UUID;

	public GenerateURL(IContext context, java.lang.String UUID)
	{
		super(context);
		this.UUID = UUID;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String url = Core.getConfiguration().getApplicationRootUrl();
		
		if( !url.endsWith("/") )
			url += "/";
		
		url += "link/";
		url += "ForgotPassword?GUID=" + this.UUID;
		return url;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateURL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
