// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forgotpassword.proxies;

public class Configuration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ForgotPassword.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HasTemplate("HasTemplate"),
		HasDeeplink("HasDeeplink"),
		HasSignUpTemplate("HasSignUpTemplate"),
		Configuration_EmailTemplate_Reset("ForgotPassword.Configuration_EmailTemplate_Reset"),
		Configuration_DeepLink("ForgotPassword.Configuration_DeepLink"),
		Configuration_EmailTemplate_Signup("ForgotPassword.Configuration_EmailTemplate_Signup");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ForgotPassword.Configuration"));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ForgotPassword.Configuration", configurationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ForgotPassword.Configuration");

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Configuration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static forgotpassword.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return forgotpassword.proxies.Configuration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static forgotpassword.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forgotpassword.proxies.Configuration(context, mendixObject);
	}

	public static forgotpassword.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forgotpassword.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<forgotpassword.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<forgotpassword.proxies.Configuration> result = new java.util.ArrayList<forgotpassword.proxies.Configuration>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ForgotPassword.Configuration" + xpathConstraint))
			result.add(forgotpassword.proxies.Configuration.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of HasTemplate
	 */
	public final java.lang.Boolean getHasTemplate()
	{
		return getHasTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of HasTemplate
	 */
	public final java.lang.Boolean getHasTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasTemplate.toString());
	}

	/**
	 * Set value of HasTemplate
	 * @param hastemplate
	 */
	public final void setHasTemplate(java.lang.Boolean hastemplate)
	{
		setHasTemplate(getContext(), hastemplate);
	}

	/**
	 * Set value of HasTemplate
	 * @param context
	 * @param hastemplate
	 */
	public final void setHasTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hastemplate)
	{
		getMendixObject().setValue(context, MemberNames.HasTemplate.toString(), hastemplate);
	}

	/**
	 * @return value of HasDeeplink
	 */
	public final java.lang.Boolean getHasDeeplink()
	{
		return getHasDeeplink(getContext());
	}

	/**
	 * @param context
	 * @return value of HasDeeplink
	 */
	public final java.lang.Boolean getHasDeeplink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasDeeplink.toString());
	}

	/**
	 * Set value of HasDeeplink
	 * @param hasdeeplink
	 */
	public final void setHasDeeplink(java.lang.Boolean hasdeeplink)
	{
		setHasDeeplink(getContext(), hasdeeplink);
	}

	/**
	 * Set value of HasDeeplink
	 * @param context
	 * @param hasdeeplink
	 */
	public final void setHasDeeplink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasdeeplink)
	{
		getMendixObject().setValue(context, MemberNames.HasDeeplink.toString(), hasdeeplink);
	}

	/**
	 * @return value of HasSignUpTemplate
	 */
	public final java.lang.Boolean getHasSignUpTemplate()
	{
		return getHasSignUpTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of HasSignUpTemplate
	 */
	public final java.lang.Boolean getHasSignUpTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasSignUpTemplate.toString());
	}

	/**
	 * Set value of HasSignUpTemplate
	 * @param hassignuptemplate
	 */
	public final void setHasSignUpTemplate(java.lang.Boolean hassignuptemplate)
	{
		setHasSignUpTemplate(getContext(), hassignuptemplate);
	}

	/**
	 * Set value of HasSignUpTemplate
	 * @param context
	 * @param hassignuptemplate
	 */
	public final void setHasSignUpTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hassignuptemplate)
	{
		getMendixObject().setValue(context, MemberNames.HasSignUpTemplate.toString(), hassignuptemplate);
	}

	/**
	 * @return value of Configuration_EmailTemplate_Reset
	 */
	public final emailtemplate.proxies.EmailTemplate getConfiguration_EmailTemplate_Reset() throws com.mendix.core.CoreException
	{
		return getConfiguration_EmailTemplate_Reset(getContext());
	}

	/**
	 * @param context
	 * @return value of Configuration_EmailTemplate_Reset
	 */
	public final emailtemplate.proxies.EmailTemplate getConfiguration_EmailTemplate_Reset(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Configuration_EmailTemplate_Reset.toString());
		if (identifier != null)
			result = emailtemplate.proxies.EmailTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Configuration_EmailTemplate_Reset
	 * @param configuration_emailtemplate_reset
	 */
	public final void setConfiguration_EmailTemplate_Reset(emailtemplate.proxies.EmailTemplate configuration_emailtemplate_reset)
	{
		setConfiguration_EmailTemplate_Reset(getContext(), configuration_emailtemplate_reset);
	}

	/**
	 * Set value of Configuration_EmailTemplate_Reset
	 * @param context
	 * @param configuration_emailtemplate_reset
	 */
	public final void setConfiguration_EmailTemplate_Reset(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.EmailTemplate configuration_emailtemplate_reset)
	{
		if (configuration_emailtemplate_reset == null)
			getMendixObject().setValue(context, MemberNames.Configuration_EmailTemplate_Reset.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Configuration_EmailTemplate_Reset.toString(), configuration_emailtemplate_reset.getMendixObject().getId());
	}

	/**
	 * @return value of Configuration_DeepLink
	 */
	public final deeplink.proxies.DeepLink getConfiguration_DeepLink() throws com.mendix.core.CoreException
	{
		return getConfiguration_DeepLink(getContext());
	}

	/**
	 * @param context
	 * @return value of Configuration_DeepLink
	 */
	public final deeplink.proxies.DeepLink getConfiguration_DeepLink(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		deeplink.proxies.DeepLink result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Configuration_DeepLink.toString());
		if (identifier != null)
			result = deeplink.proxies.DeepLink.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Configuration_DeepLink
	 * @param configuration_deeplink
	 */
	public final void setConfiguration_DeepLink(deeplink.proxies.DeepLink configuration_deeplink)
	{
		setConfiguration_DeepLink(getContext(), configuration_deeplink);
	}

	/**
	 * Set value of Configuration_DeepLink
	 * @param context
	 * @param configuration_deeplink
	 */
	public final void setConfiguration_DeepLink(com.mendix.systemwideinterfaces.core.IContext context, deeplink.proxies.DeepLink configuration_deeplink)
	{
		if (configuration_deeplink == null)
			getMendixObject().setValue(context, MemberNames.Configuration_DeepLink.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Configuration_DeepLink.toString(), configuration_deeplink.getMendixObject().getId());
	}

	/**
	 * @return value of Configuration_EmailTemplate_Signup
	 */
	public final emailtemplate.proxies.EmailTemplate getConfiguration_EmailTemplate_Signup() throws com.mendix.core.CoreException
	{
		return getConfiguration_EmailTemplate_Signup(getContext());
	}

	/**
	 * @param context
	 * @return value of Configuration_EmailTemplate_Signup
	 */
	public final emailtemplate.proxies.EmailTemplate getConfiguration_EmailTemplate_Signup(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emailtemplate.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Configuration_EmailTemplate_Signup.toString());
		if (identifier != null)
			result = emailtemplate.proxies.EmailTemplate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Configuration_EmailTemplate_Signup
	 * @param configuration_emailtemplate_signup
	 */
	public final void setConfiguration_EmailTemplate_Signup(emailtemplate.proxies.EmailTemplate configuration_emailtemplate_signup)
	{
		setConfiguration_EmailTemplate_Signup(getContext(), configuration_emailtemplate_signup);
	}

	/**
	 * Set value of Configuration_EmailTemplate_Signup
	 * @param context
	 * @param configuration_emailtemplate_signup
	 */
	public final void setConfiguration_EmailTemplate_Signup(com.mendix.systemwideinterfaces.core.IContext context, emailtemplate.proxies.EmailTemplate configuration_emailtemplate_signup)
	{
		if (configuration_emailtemplate_signup == null)
			getMendixObject().setValue(context, MemberNames.Configuration_EmailTemplate_Signup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Configuration_EmailTemplate_Signup.toString(), configuration_emailtemplate_signup.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forgotpassword.proxies.Configuration that = (forgotpassword.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ForgotPassword.Configuration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
