// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forgotpassword.proxies;

public class ForgotPassword
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject forgotPasswordMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ForgotPassword.ForgotPassword";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EmailAddress("EmailAddress"),
		Username("Username"),
		UserFullname("UserFullname"),
		ForgotPasswordGUID("ForgotPasswordGUID"),
		ForgotPasswordURL("ForgotPasswordURL"),
		ValidUntill("ValidUntill"),
		IsSignUp("IsSignUp"),
		ForgotPassword_Account("ForgotPassword.ForgotPassword_Account"),
		ForgotPassword_Anon_User_Access("ForgotPassword.ForgotPassword_Anon_User_Access");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ForgotPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ForgotPassword.ForgotPassword"));
	}

	protected ForgotPassword(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject forgotPasswordMendixObject)
	{
		if (forgotPasswordMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ForgotPassword.ForgotPassword", forgotPasswordMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ForgotPassword.ForgotPassword");

		this.forgotPasswordMendixObject = forgotPasswordMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ForgotPassword.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static forgotpassword.proxies.ForgotPassword initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return forgotpassword.proxies.ForgotPassword.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static forgotpassword.proxies.ForgotPassword initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forgotpassword.proxies.ForgotPassword(context, mendixObject);
	}

	public static forgotpassword.proxies.ForgotPassword load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forgotpassword.proxies.ForgotPassword.initialize(context, mendixObject);
	}

	public static java.util.List<forgotpassword.proxies.ForgotPassword> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<forgotpassword.proxies.ForgotPassword> result = new java.util.ArrayList<forgotpassword.proxies.ForgotPassword>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ForgotPassword.ForgotPassword" + xpathConstraint))
			result.add(forgotpassword.proxies.ForgotPassword.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of UserFullname
	 */
	public final java.lang.String getUserFullname()
	{
		return getUserFullname(getContext());
	}

	/**
	 * @param context
	 * @return value of UserFullname
	 */
	public final java.lang.String getUserFullname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserFullname.toString());
	}

	/**
	 * Set value of UserFullname
	 * @param userfullname
	 */
	public final void setUserFullname(java.lang.String userfullname)
	{
		setUserFullname(getContext(), userfullname);
	}

	/**
	 * Set value of UserFullname
	 * @param context
	 * @param userfullname
	 */
	public final void setUserFullname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userfullname)
	{
		getMendixObject().setValue(context, MemberNames.UserFullname.toString(), userfullname);
	}

	/**
	 * @return value of ForgotPasswordGUID
	 */
	public final java.lang.String getForgotPasswordGUID()
	{
		return getForgotPasswordGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of ForgotPasswordGUID
	 */
	public final java.lang.String getForgotPasswordGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ForgotPasswordGUID.toString());
	}

	/**
	 * Set value of ForgotPasswordGUID
	 * @param forgotpasswordguid
	 */
	public final void setForgotPasswordGUID(java.lang.String forgotpasswordguid)
	{
		setForgotPasswordGUID(getContext(), forgotpasswordguid);
	}

	/**
	 * Set value of ForgotPasswordGUID
	 * @param context
	 * @param forgotpasswordguid
	 */
	public final void setForgotPasswordGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String forgotpasswordguid)
	{
		getMendixObject().setValue(context, MemberNames.ForgotPasswordGUID.toString(), forgotpasswordguid);
	}

	/**
	 * @return value of ForgotPasswordURL
	 */
	public final java.lang.String getForgotPasswordURL()
	{
		return getForgotPasswordURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ForgotPasswordURL
	 */
	public final java.lang.String getForgotPasswordURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ForgotPasswordURL.toString());
	}

	/**
	 * Set value of ForgotPasswordURL
	 * @param forgotpasswordurl
	 */
	public final void setForgotPasswordURL(java.lang.String forgotpasswordurl)
	{
		setForgotPasswordURL(getContext(), forgotpasswordurl);
	}

	/**
	 * Set value of ForgotPasswordURL
	 * @param context
	 * @param forgotpasswordurl
	 */
	public final void setForgotPasswordURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String forgotpasswordurl)
	{
		getMendixObject().setValue(context, MemberNames.ForgotPasswordURL.toString(), forgotpasswordurl);
	}

	/**
	 * @return value of ValidUntill
	 */
	public final java.util.Date getValidUntill()
	{
		return getValidUntill(getContext());
	}

	/**
	 * @param context
	 * @return value of ValidUntill
	 */
	public final java.util.Date getValidUntill(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ValidUntill.toString());
	}

	/**
	 * Set value of ValidUntill
	 * @param validuntill
	 */
	public final void setValidUntill(java.util.Date validuntill)
	{
		setValidUntill(getContext(), validuntill);
	}

	/**
	 * Set value of ValidUntill
	 * @param context
	 * @param validuntill
	 */
	public final void setValidUntill(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date validuntill)
	{
		getMendixObject().setValue(context, MemberNames.ValidUntill.toString(), validuntill);
	}

	/**
	 * @return value of IsSignUp
	 */
	public final java.lang.Boolean getIsSignUp()
	{
		return getIsSignUp(getContext());
	}

	/**
	 * @param context
	 * @return value of IsSignUp
	 */
	public final java.lang.Boolean getIsSignUp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsSignUp.toString());
	}

	/**
	 * Set value of IsSignUp
	 * @param issignup
	 */
	public final void setIsSignUp(java.lang.Boolean issignup)
	{
		setIsSignUp(getContext(), issignup);
	}

	/**
	 * Set value of IsSignUp
	 * @param context
	 * @param issignup
	 */
	public final void setIsSignUp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issignup)
	{
		getMendixObject().setValue(context, MemberNames.IsSignUp.toString(), issignup);
	}

	/**
	 * @return value of ForgotPassword_Account
	 */
	public final administration.proxies.Account getForgotPassword_Account() throws com.mendix.core.CoreException
	{
		return getForgotPassword_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of ForgotPassword_Account
	 */
	public final administration.proxies.Account getForgotPassword_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ForgotPassword_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ForgotPassword_Account
	 * @param forgotpassword_account
	 */
	public final void setForgotPassword_Account(administration.proxies.Account forgotpassword_account)
	{
		setForgotPassword_Account(getContext(), forgotpassword_account);
	}

	/**
	 * Set value of ForgotPassword_Account
	 * @param context
	 * @param forgotpassword_account
	 */
	public final void setForgotPassword_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account forgotpassword_account)
	{
		if (forgotpassword_account == null)
			getMendixObject().setValue(context, MemberNames.ForgotPassword_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ForgotPassword_Account.toString(), forgotpassword_account.getMendixObject().getId());
	}

	/**
	 * @return value of ForgotPassword_Anon_User_Access
	 */
	public final java.util.List<system.proxies.User> getForgotPassword_Anon_User_Access() throws com.mendix.core.CoreException
	{
		return getForgotPassword_Anon_User_Access(getContext());
	}

	/**
	 * @param context
	 * @return value of ForgotPassword_Anon_User_Access
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.User> getForgotPassword_Anon_User_Access(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.User> result = new java.util.ArrayList<system.proxies.User>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ForgotPassword_Anon_User_Access.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(system.proxies.User.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ForgotPassword_Anon_User_Access
	 * @param forgotpassword_anon_user_access
	 */
	public final void setForgotPassword_Anon_User_Access(java.util.List<system.proxies.User> forgotpassword_anon_user_access)
	{
		setForgotPassword_Anon_User_Access(getContext(), forgotpassword_anon_user_access);
	}

	/**
	 * Set value of ForgotPassword_Anon_User_Access
	 * @param context
	 * @param forgotpassword_anon_user_access
	 */
	public final void setForgotPassword_Anon_User_Access(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.User> forgotpassword_anon_user_access)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (system.proxies.User proxyObject : forgotpassword_anon_user_access)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ForgotPassword_Anon_User_Access.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return forgotPasswordMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forgotpassword.proxies.ForgotPassword that = (forgotpassword.proxies.ForgotPassword) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ForgotPassword.ForgotPassword";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
