// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forgotpassword.proxies;

public class SignupHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject signupHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ForgotPassword.SignupHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserFullname("UserFullname"),
		EmailAddress("EmailAddress"),
		SignupHelper_ForgotPassword("ForgotPassword.SignupHelper_ForgotPassword");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SignupHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ForgotPassword.SignupHelper"));
	}

	protected SignupHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject signupHelperMendixObject)
	{
		if (signupHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ForgotPassword.SignupHelper", signupHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ForgotPassword.SignupHelper");

		this.signupHelperMendixObject = signupHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SignupHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static forgotpassword.proxies.SignupHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return forgotpassword.proxies.SignupHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static forgotpassword.proxies.SignupHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forgotpassword.proxies.SignupHelper(context, mendixObject);
	}

	public static forgotpassword.proxies.SignupHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forgotpassword.proxies.SignupHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UserFullname
	 */
	public final java.lang.String getUserFullname()
	{
		return getUserFullname(getContext());
	}

	/**
	 * @param context
	 * @return value of UserFullname
	 */
	public final java.lang.String getUserFullname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserFullname.toString());
	}

	/**
	 * Set value of UserFullname
	 * @param userfullname
	 */
	public final void setUserFullname(java.lang.String userfullname)
	{
		setUserFullname(getContext(), userfullname);
	}

	/**
	 * Set value of UserFullname
	 * @param context
	 * @param userfullname
	 */
	public final void setUserFullname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userfullname)
	{
		getMendixObject().setValue(context, MemberNames.UserFullname.toString(), userfullname);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of SignupHelper_ForgotPassword
	 */
	public final forgotpassword.proxies.ForgotPassword getSignupHelper_ForgotPassword() throws com.mendix.core.CoreException
	{
		return getSignupHelper_ForgotPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of SignupHelper_ForgotPassword
	 */
	public final forgotpassword.proxies.ForgotPassword getSignupHelper_ForgotPassword(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		forgotpassword.proxies.ForgotPassword result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SignupHelper_ForgotPassword.toString());
		if (identifier != null)
			result = forgotpassword.proxies.ForgotPassword.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SignupHelper_ForgotPassword
	 * @param signuphelper_forgotpassword
	 */
	public final void setSignupHelper_ForgotPassword(forgotpassword.proxies.ForgotPassword signuphelper_forgotpassword)
	{
		setSignupHelper_ForgotPassword(getContext(), signuphelper_forgotpassword);
	}

	/**
	 * Set value of SignupHelper_ForgotPassword
	 * @param context
	 * @param signuphelper_forgotpassword
	 */
	public final void setSignupHelper_ForgotPassword(com.mendix.systemwideinterfaces.core.IContext context, forgotpassword.proxies.ForgotPassword signuphelper_forgotpassword)
	{
		if (signuphelper_forgotpassword == null)
			getMendixObject().setValue(context, MemberNames.SignupHelper_ForgotPassword.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SignupHelper_ForgotPassword.toString(), signuphelper_forgotpassword.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return signupHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forgotpassword.proxies.SignupHelper that = (forgotpassword.proxies.SignupHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ForgotPassword.SignupHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
