// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the EmailTemplate module
	public static boolean bCo_EmailSettings(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "EmailTemplate.BCo_EmailSettings", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Long countNrOfTemplates(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Long)Core.execute(context, "EmailTemplate.CountNrOfTemplates", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static emailtemplate.proxies.ModuleSetup dS_CheckForSetup(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "EmailTemplate.DS_CheckForSetup", params);
			return result == null ? null : emailtemplate.proxies.ModuleSetup.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static emailtemplate.proxies.EmailSettings dS_GetEmailSettings(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "EmailTemplate.DS_GetEmailSettings", params);
			return result == null ? null : emailtemplate.proxies.EmailSettings.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static emailtemplate.proxies.EmailTemplate dS_GetFirstTemplate(IContext context, emailtemplate.proxies.ModuleSetup _moduleSetup)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ModuleSetup", _moduleSetup == null ? null : _moduleSetup.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "EmailTemplate.DS_GetFirstTemplate", params);
			return result == null ? null : emailtemplate.proxies.EmailTemplate.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ChangePortSSL(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_ChangePortSSL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ChangePortTLS(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_ChangePortTLS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateTestEmail(IContext context, emailtemplate.proxies.ModuleSetup _moduleSetup)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ModuleSetup", _moduleSetup == null ? null : _moduleSetup.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_CreateTestEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateTestMessage(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_CreateTestMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_DownloadAttachment(IContext context, emailtemplate.proxies.Attachment _attachment)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Attachment", _attachment == null ? null : _attachment.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_DownloadAttachment", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_DuplicateEmailTemplate(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_DuplicateEmailTemplate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_EmailSettingsWizard_edit(IContext context, emailtemplate.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_EmailSettingsWizard_edit", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Emailtemplate_NewToken(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_Emailtemplate_NewToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_GeneratePlainText(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_GeneratePlainText", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ResendFailedEmail(IContext context, emailtemplate.proxies.Email _email)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Email", _email == null ? null : _email.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_ResendFailedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ResendFailedEmails(IContext context, java.util.List<emailtemplate.proxies.Email> _emailList)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_emailList = null;
			if (_emailList != null)
			{
				listparam_emailList = new java.util.ArrayList<IMendixObject>();
				for (emailtemplate.proxies.Email obj : _emailList)
					listparam_emailList.add(obj.getMendixObject());
			}
			params.put("EmailList", listparam_emailList);
			Core.execute(context, "EmailTemplate.IVK_ResendFailedEmails", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveEmailSettings(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveEmailSettings", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveEmailSettingsFromTestMessage(IContext context, emailtemplate.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveEmailSettingsFromTestMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveEmailTemplate(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveEmailTemplate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveStep1(IContext context, emailtemplate.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveStep1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveStep2(IContext context, emailtemplate.proxies.ModuleSetup _moduleSetup)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ModuleSetup", _moduleSetup == null ? null : _moduleSetup.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveStep2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SendEmail(IContext context, emailtemplate.proxies.Email _newEmail)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("NewEmail", _newEmail == null ? null : _newEmail.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SendEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SendTestMessage(IContext context, emailtemplate.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SendTestMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SkipTestEmail(IContext context, emailtemplate.proxies.TestMessage _testMessage)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TestMessage", _testMessage == null ? null : _testMessage.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SkipTestEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_SSL(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.OC_SSL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_TLS(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.OC_TLS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_SSL(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.OCh_SSL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_TLS(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.OCh_TLS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sE_Cleanup(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "EmailTemplate.SE_Cleanup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sE_SendQueuedEmails(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "EmailTemplate.SE_SendQueuedEmails", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sendEmailMessage(IContext context, java.lang.String _from, java.lang.String _to, java.lang.String _subject, java.lang.String _hTMLBody, java.lang.String _plainTextBody, java.lang.String _cC, java.lang.String _bCC, emailtemplate.proxies.EmailSettings _emailSettings, java.util.List<emailtemplate.proxies.Attachment> _attachmentList, java.util.List<emailtemplate.proxies.Header> _headerList, java.lang.String _replyTo, java.lang.String _fromDisplayName)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("From", _from);
			params.put("To", _to);
			params.put("Subject", _subject);
			params.put("HTMLBody", _hTMLBody);
			params.put("PlainTextBody", _plainTextBody);
			params.put("CC", _cC);
			params.put("BCC", _bCC);
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			java.util.ArrayList<IMendixObject> listparam_attachmentList = null;
			if (_attachmentList != null)
			{
				listparam_attachmentList = new java.util.ArrayList<IMendixObject>();
				for (emailtemplate.proxies.Attachment obj : _attachmentList)
					listparam_attachmentList.add(obj.getMendixObject());
			}
			params.put("AttachmentList", listparam_attachmentList);
			java.util.ArrayList<IMendixObject> listparam_headerList = null;
			if (_headerList != null)
			{
				listparam_headerList = new java.util.ArrayList<IMendixObject>();
				for (emailtemplate.proxies.Header obj : _headerList)
					listparam_headerList.add(obj.getMendixObject());
			}
			params.put("HeaderList", listparam_headerList);
			params.put("ReplyTo", _replyTo);
			params.put("FromDisplayName", _fromDisplayName);
			return (java.lang.Boolean)Core.execute(context, "EmailTemplate.SendEmailMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<emailtemplate.proxies.Attachment> sub_CreateAttachments(IContext context, java.util.List<system.proxies.FileDocument> _fileDocumentList, emailtemplate.proxies.Email _email)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_fileDocumentList = null;
			if (_fileDocumentList != null)
			{
				listparam_fileDocumentList = new java.util.ArrayList<IMendixObject>();
				for (system.proxies.FileDocument obj : _fileDocumentList)
					listparam_fileDocumentList.add(obj.getMendixObject());
			}
			params.put("FileDocumentList", listparam_fileDocumentList);
			params.put("Email", _email == null ? null : _email.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "EmailTemplate.Sub_CreateAttachments", params);
			java.util.List<emailtemplate.proxies.Attachment> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<emailtemplate.proxies.Attachment>();
				for (IMendixObject obj : objs)
					result.add(emailtemplate.proxies.Attachment.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sub_CreateLogItem(IContext context, java.lang.String _triggeredInMF, emailtemplate.proxies.LogType _logType, java.lang.String _message, java.lang.String _errorMessage, java.lang.String _stackTrace)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("TriggeredInMF", _triggeredInMF);
			params.put("LogType", _logType == null ? null : _logType.name());
			params.put("Message", _message);
			params.put("ErrorMessage", _errorMessage);
			params.put("StackTrace", _stackTrace);
			Core.execute(context, "EmailTemplate.Sub_CreateLogItem", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.Token> sub_DuplicateTokenList(IContext context, java.util.List<mxmodelreflection.proxies.Token> _tokenList)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_tokenList = null;
			if (_tokenList != null)
			{
				listparam_tokenList = new java.util.ArrayList<IMendixObject>();
				for (mxmodelreflection.proxies.Token obj : _tokenList)
					listparam_tokenList.add(obj.getMendixObject());
			}
			params.put("TokenList", listparam_tokenList);
			java.util.List<IMendixObject> objs = Core.execute(context, "EmailTemplate.Sub_DuplicateTokenList", params);
			java.util.List<mxmodelreflection.proxies.Token> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.Token>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.Token.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sub_SendQueuedEmail(IContext context, emailtemplate.proxies.Email _email, emailtemplate.proxies.EmailSettings _emailSettings, java.lang.String _decryptedPassword)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Email", _email == null ? null : _email.getMendixObject());
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			params.put("DecryptedPassword", _decryptedPassword);
			Core.execute(context, "EmailTemplate.Sub_SendQueuedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sub_SendSimpleEmail(IContext context, java.lang.String _to)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("To", _to);
			Core.execute(context, "EmailTemplate.Sub_SendSimpleEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}