// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forgotpassword.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the ForgotPassword module
	public static boolean cA_ConfigurationHasDeeplink(IContext context, forgotpassword.proxies.Configuration _configuration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "ForgotPassword.CA_ConfigurationHasDeeplink", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean cA_ConfigurationHasEmailTemplate_Reset(IContext context, forgotpassword.proxies.Configuration _configuration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "ForgotPassword.CA_ConfigurationHasEmailTemplate_Reset", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean cA_ConfigurationHasEmailTemplate_Signup(IContext context, forgotpassword.proxies.Configuration _configuration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "ForgotPassword.CA_ConfigurationHasEmailTemplate_Signup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createNewUserFromSignup(IContext context, forgotpassword.proxies.ForgotPassword _forgotPassword)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ForgotPassword", _forgotPassword == null ? null : _forgotPassword.getMendixObject());
			Core.execute(context, "ForgotPassword.CreateNewUserFromSignup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static forgotpassword.proxies.Configuration dV_GetConfiguration(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "ForgotPassword.DV_GetConfiguration", params);
			return result == null ? null : forgotpassword.proxies.Configuration.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void generateUIDAndURL(IContext context, forgotpassword.proxies.ForgotPassword _forgotPassword)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ForgotPassword", _forgotPassword == null ? null : _forgotPassword.getMendixObject());
			Core.execute(context, "ForgotPassword.GenerateUIDAndURL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateDeeplink(IContext context, forgotpassword.proxies.Configuration _configuration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
			Core.execute(context, "ForgotPassword.IVK_CreateDeeplink", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateEmailTemplate_Reset(IContext context, forgotpassword.proxies.Configuration _configuration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
			Core.execute(context, "ForgotPassword.IVK_CreateEmailTemplate_Reset", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_CreateEmailTemplate_Signup(IContext context, forgotpassword.proxies.Configuration _configuration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
			Core.execute(context, "ForgotPassword.IVK_CreateEmailTemplate_Signup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Step2_SendConfirmationEmail(IContext context, forgotpassword.proxies.SignupHelper _signupHelper)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SignupHelper", _signupHelper == null ? null : _signupHelper.getMendixObject());
			Core.execute(context, "ForgotPassword.MB_Step2_SendConfirmationEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void nav_GuestHomePage(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "ForgotPassword.Nav_GuestHomePage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sF_CheckForDuplicateAccount(IContext context, java.lang.String _emailAddress)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailAddress", _emailAddress);
			return (java.lang.Boolean)Core.execute(context, "ForgotPassword.SF_CheckForDuplicateAccount", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sF_CreateAndSendEmail(IContext context, forgotpassword.proxies.ForgotPassword _forgotPassword, boolean _isSignUp)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ForgotPassword", _forgotPassword == null ? null : _forgotPassword.getMendixObject());
			params.put("IsSignUp", _isSignUp);
			return (java.lang.Boolean)Core.execute(context, "ForgotPassword.SF_CreateAndSendEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static forgotpassword.proxies.ForgotPassword sF_CreateForgotPasswordRequest(IContext context, java.lang.String _emailAddress)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailAddress", _emailAddress);
			IMendixObject result = (IMendixObject)Core.execute(context, "ForgotPassword.SF_CreateForgotPasswordRequest", params);
			return result == null ? null : forgotpassword.proxies.ForgotPassword.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sF_SendEmailRecoverPassword(IContext context, java.lang.String _emailAddress)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailAddress", _emailAddress);
			Core.execute(context, "ForgotPassword.SF_SendEmailRecoverPassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void step1_ShowForgotPasswordPage(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "ForgotPassword.Step1_ShowForgotPasswordPage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void step1_ShowSignupPage(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "ForgotPassword.Step1_ShowSignupPage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void step2_SendEmailRecoverPassword(IContext context, forgotpassword.proxies.ForgotPasswordHelper _forgotPasswordHelper)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ForgotPasswordHelper", _forgotPasswordHelper == null ? null : _forgotPasswordHelper.getMendixObject());
			Core.execute(context, "ForgotPassword.Step2_SendEmailRecoverPassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void step3_DL_SetNewPassword(IContext context, java.lang.String _gUID)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("GUID", _gUID);
			Core.execute(context, "ForgotPassword.Step3_DL_SetNewPassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void step4_SubmitPassword(IContext context, forgotpassword.proxies.AccountPasswordData _accountPasswordData)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AccountPasswordData", _accountPasswordData == null ? null : _accountPasswordData.getMendixObject());
			Core.execute(context, "ForgotPassword.Step4_SubmitPassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean userAccountValidation(IContext context, java.lang.String _emailAddress)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailAddress", _emailAddress);
			return (java.lang.Boolean)Core.execute(context, "ForgotPassword.UserAccountValidation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}